### ISSUE TITLE
EquivlentExpression-mapper should not check for null-values in IsMatch-method

### ISSUE THREAD

**Issue by Tasteful** [TylerCarlson1/Automapper.Collection#1]
When I using the the collection mapper with entities loaded from EF7 the equivlent expression mapper return that it not shoul be used for the type. The IsMatch method should only verify the type of the data, not if the data contains any values.

I was not able to get the same issue when I not was using EF7 and putting together a simple unit-test was not succeeded either.

**Comment by TylerCarlson1** [comment]
I don't know about this change.  The idea is if the source or the destination is null, then it's impossible to do comparison against the two lists, so the array mapper in AutoMapper should be used instead.

One thing with EF6 is that in order to save I can't new up the Poco objects.  I have to do Table<T>().CreateNew() in order to get an object that I can save back to the database.
Also can you default your lists to be not null, to fix this problem?

Can you give me an example of code that fails, with error message, or issue in more detail?

**Comment by Tasteful** [comment]
I created a test class project here: https://github.com/Tasteful/Automapper.Collection/tree/Tests

That will have 2 tests that should be run individual, otherwise the mappings will be wrong.
One test is with the original code and the other one is with the updated mapper from the #2 PR.

The exception that will be thrown is shown in this capture.
![image](https://cloud.githubusercontent.com/assets/357589/10546930/565ecefe-7431-11e5-8aa7-96d9bb69c11c.png)

**Comment by Tasteful** [comment]
Also if we look at the other mappers that is in AutoMapper they will not either check for null-values. I have not going down in AutoMappers code but it can be that AutoMapper are caching the IObjectMapper the type->type should use and in that case if the source or destination value is null it will not store the IObjectMapper as possible mapping of the types.

**Comment by TylerCarlson1** [comment]
Can you set ProductDto.FieldData to equal a new list in the constructor and have that fix the problem?  Or make it virtual?  I know in EF 6 you had to make it virtual so that when the proxy class around it was generated it could overwrite the list with the data from the DBContext.  That could be why it's null and failing to map over.  I don't know if EF 7 handles this the same way, but I would believe it would.

Can't build it right now to test this out, but can try over the weekend if need be.

Also names are backwards.  Dto's should not be the EF objects but the ones the EF objects transfer over too.  Not critical, but names threw me off at first glance.

**Comment by Tasteful** [comment]
I can try and see if the error still are there if I set the collection in
the ctor.

For the moment I use an private build with my fixes in that I also added
strong naming to. I would like to not have to maintain an own version.

On 16 Oct 2015 19:24, "Tyler Carlson" <notifications@github.com> wrote:
>
> Can you set ProductDto.FieldData to equal a new list in the constructor
and have that fix the problem? Or make it virtual? I know in EF 6 you had
to make it virtual so that when the proxy class around it was generated it
could overwrite the list with the data from the DBContext. That could be
why it's null and failing to map over. I don't know if EF 7 handles this
the same way, but I would believe it would.
>
> Can't build it right now to test this out, but can try over the weekend
if need be.
>
> Also names are backwards. Dto's should not be the EF objects but the ones
the EF objects transfer over too. Not critical, but names threw me off at
first glance.

**Comment by Tasteful** [comment]
I tested to initiate the collections in the ctor and then the default implementation is working. But the IsMatch should not check null values. If we check automapper-code https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/MappingEngine.cs#L404 we can see that AutoMapper will cache the fist IObjectMapper that will get hit for the source and destination type. If one of the values is null the first execution the mapping cache will contains wrong record. If the ArrayMapper should be used if some of the values was null the ArrayMapper should probably be executed as a base class for the current implementation.

**Comment by TylerCarlson1** [comment]
I never noticed that.  Would assume it would check multiple times.  And in EF 6 I would use CreateNew<T> instead of new T which would never have nulls and this problem never showed itself explicitly.

Will have to bring this issue up in AutoMapper, because other things might have this problem.  Maybe make IsMatch only uses TypePair.

I agree with you now this has to be changed.

**Comment by TylerCarlson1** [comment]
Also updated tests to do auto-generated equivalency expression
https://github.com/TylerCarlson1/Automapper.Collection/tree/Tests

Can't run tests right now, but that should be the gist of what you need to not have to write an EqualityComparision for every mapping.  Thankfully they made finding the Model and Primary Keys super easy compared to EF6.

**Comment by Tasteful** [comment]
I will merge them down and test tomorrow.

How is the autofinding part working when the entity in database has an composit key over multiple colums but in the entity that it got translated to is missing one of the fields, can it map the other colums automatomatic?

**Comment by TylerCarlson1** [comment]
If you have a composite key you must have mappings from all columns in the key in order to make a valid equivalency expression and have the collection mapper be used in the mapping.

If you look at `GenerateEquivilentExpressionsBasedOnGeneratePropertyMaps` the logic for this is there, but you can always make a new class and make it work out differently.  You can always override this behavior by using `EqualityExpression` if you have a rare or unique scenario.  You can make your own rules to do whatever you want,  I just made it for EF's primary keys and only if all have property maps.

**Comment by TylerCarlson1** [comment]
Updated logic to not include nulls on IsMatch, but if source or destination is null on map use CollectionMapper to resolve.  Don't want to duplicate code if I don't have to.  And it was my original intent to fall back on CollectionMapper.

**Comment by TylerCarlson1** [comment]
Did the `GenerateEquivilentExpressionsBasedOnGeneratePropertyMaps` work, or was of any help for EF7?

**Comment by Tasteful** [comment]
I didn't try. I only use a part of the primary key as the key for
collection mapping.
